import os
import re
import csv
from src.data.scraper import extract_sections  # Reuse scraper's core extraction logic
from src.data.config import CORPUS_DIR, AUDIT_FILE

# --- CONFIGURATION ---
INPUT_DIR   = CORPUS_DIR
REPORT_FILE = AUDIT_FILE


def is_ghost_file(content):
    """Detects if the file is just an empty E-Library placeholder."""
    if len(content) < 1000:
        if "dynamically generated by the E-Library Content Management System" in content:
            return True
        if "========== FACTS ==========" in content and "========== RULING ==========" in content:
            clean = content.replace("========== FACTS ==========", "").replace("========== RULING ==========", "")
            clean = re.sub(r"\s+", "", clean)
            if len(clean) < 50:
                return True
    return False


def fix_files():
    if not os.path.exists(REPORT_FILE):
        print(f"Report '{REPORT_FILE}' not found. Run auditor.py first.")
        return

    # 1. Load the list of bad files
    files_to_fix = []
    with open(REPORT_FILE, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            files_to_fix.append(row['filename'])

    print(f"Processing {len(files_to_fix)} flagged files...\n")
    fixed_count = 0
    deleted_count = 0
    failed_count = 0

    for filename in files_to_fix:
        filepath = os.path.join(INPUT_DIR, filename)

        if not os.path.exists(filepath):
            continue

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()

            # --- GHOST BUSTER CHECK ---
            if is_ghost_file(content):
                os.remove(filepath)
                print(f"👻 Deleted Ghost File: {filename}")
                deleted_count += 1
                continue

            # 3. Recover the "Raw Text"
            if "========== FACTS ==========" in content:
                parts = content.split("========== FACTS ==========")
                header_part = parts[0].strip()
                url_line = next((line for line in header_part.split('\n') if "URL:" in line), "URL: Unknown")

                if "========== RULING ==========" in parts[1]:
                    split_parts = parts[1].split("========== RULING ==========")
                    raw_facts = split_parts[0].strip()
                    raw_ruling = split_parts[1].strip()
                    combined_text = raw_facts + "\n\n" + raw_ruling
                else:
                    combined_text = parts[1].strip()
            else:
                print(f"Skipping {filename}: Could not parse structure.")
                failed_count += 1
                continue

            # 4. Apply the Scraper's Logic (The "Healing" Process)
            new_sections = extract_sections(combined_text)

            # --- FOOTNOTE GUILLOTINE ---
            if len(new_sections['ruling']) > 0:
                sample = new_sections['ruling'][:100]
                if re.match(r"^[\s\d\.\-Id\sat,]+$", sample):
                    if "SO ORDERED" in new_sections['facts']:
                        so_ordered_idx = new_sections['facts'].rfind("SO ORDERED")
                        last_para = new_sections['facts'].rfind("\n", 0, so_ordered_idx)

                        if last_para != -1:
                            new_sections['ruling'] = new_sections['facts'][last_para:].strip()
                            new_sections['facts'] = new_sections['facts'][:last_para].strip()
                            new_sections['status'] = "SPLIT_RESCUED_FROM_FOOTNOTES"

            # 5. Overwrite the file
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(f"{url_line}\n")
                f.write(f"STATUS: {new_sections['status']} (FIXED)\n")
                f.write("="*20 + " FACTS " + "="*20 + "\n")
                f.write(new_sections['facts'] + "\n\n")
                f.write("="*20 + " RULING " + "="*20 + "\n")
                f.write(new_sections['ruling'] + "\n")

            print(f"Fixed: {filename} -> {new_sections['status']}")
            fixed_count += 1

        except Exception as e:
            print(f"Failed to fix {filename}: {e}")
            failed_count += 1

    print("\n" + "=" * 40)
    print(f"FIX RESULTS")
    print(f"✅ Reprocessed: {fixed_count}")
    print(f"👻 Deleted:     {deleted_count}")
    print(f"❌ Failed:      {failed_count}")
    print("=" * 40)
    print("Run auditor.py again to verify repairs.")


if __name__ == "__main__":
    fix_files()
